name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3
    - name: Use Node.js 20
      uses: actions/setup-node@v3
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Install dependencies
      run: npm install
    - name: Replace the config settings
      run: echo "export const settings = {host:\"http://localhost3030\"} > src/config.js" 
    - name: Start BackEnd
      run: npm run start-be &
    - name: Sleep 5 seconds 
      run: sleep 5 seconds
    - name: Start FrontEnd
      run: npm run start-fe &
    - name: Sleep 5 seconds 
      run: sleep 5 seconds
    - name: Install Playright
      run:  npx playwright install     
    - name: Test UI interface
      run: npm run test-ui

  deploy-be:
      runs-on: ubuntu-latest
      needs: build-and-test
      steps:
        - name: Deploy to production
          uses: johnbeynon/render-deploy-action@v0.0.8
          with:
            service-id: ${{ secrets.SERVICE_BE_ID }}
            api-key: ${{ secrets.RENDER_TOKEN }}
            wait-for-success: true

  deploy-fe:
    runs-on: ubuntu-latest
    needs: deploy-be
    steps:
      - name: Deploy to production
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.SERVICE_FE_ID }}
          api-key: ${{ secrets.RENDER_TOKEN }}
          wait-for-success: true
